/*      Copyright 2002 Arizona Board of regents on behalf of 
 *                  The University of Arizona 
 *                     All Rights Reserved 
 *         (USE & RESTRICTION - Please read COPYRIGHT file) 
 * 
 *  Version    : DEVSJAVA 2.7 
 *  Date       : 08-15-02 
 */ 

package GenDevsTest;

import java.awt.*;
import java.util.*;
import GenCol.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import simView.*;
import util.*;

public class HierarModel extends ViewableDigraph
{
    public HierarModel()
    {
        super("HierarModel");

        addInport("in");
        addOutport("outFinalC2");
        addOutport("outFinalC1");

        HierarCoupledModel3 c1 = new HierarCoupledModel3();
        add(c1);

        HierarCoupledModel2 c2 = new HierarCoupledModel2();
        add(c2);

        addCoupling(this, "in", c1, "in");
        addCoupling(c1, "out", c2, "in");
        addCoupling(c2, "out", c1, "in");
        addCoupling(c2, "out", this, "outFinalC2");
        addCoupling(c1, "out", this, "outFinalC1");

        /*
         drawEventList d = new drawEventList();
         add(d);
         addCoupling(c1,"out",d,"drawString");
         addCoupling(c2,"out",d,"drawString");
         */
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1008, 444);
        if((ViewableComponent)withName("HierarCoupledModel2")!=null)
             ((ViewableComponent)withName("HierarCoupledModel2")).setPreferredLocation(new Point(139, 386));
        if((ViewableComponent)withName("HierarCoupledModel3")!=null)
             ((ViewableComponent)withName("HierarCoupledModel3")).setPreferredLocation(new Point(32, -10));
    }
}
