/*      Copyright 2002 Arizona Board of regents on behalf of 
 *                  The University of Arizona 
 *                     All Rights Reserved 
 *         (USE & RESTRICTION - Please read COPYRIGHT file) 
 * 
 *  Version    : DEVSJAVA 2.7 
 *  Date       : 08-15-02 
 */ 


package GenDevsTest;

import java.awt.*;
import GenCol.*;
import java.util.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import simView.*;

public class HierarCoupledModel2 extends ViewableDigraph
{
    public HierarCoupledModel2()
    {
        super("HierarCoupledModel2");
        addInport("in");
        addOutport("out");
        HierarAtomicModel fourth = new HierarAtomicModel("fourth");
        HierarAtomicModel fifth = new HierarAtomicModel("fifth");
        add(fourth);
        add(fifth);
        addCoupling(fourth, "out", fifth, "start");
        addCoupling(fifth, "out", this, "out");
        addCoupling(this, "in", fourth, "start");
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(495, 94);
        ((ViewableComponent)withName("fourth")).setPreferredLocation(new Point(0, 24));
        ((ViewableComponent)withName("fifth")).setPreferredLocation(new Point(196, 22));
    }
}
